version: '3.8'

services:
  app:
    build: .
    container_name: ci4_app
    volumes:
      - .:/var/www/html
    ports:
      - "8081:80"  # changed from 8080 to 8081 to avoid conflicts
    working_dir: /var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: ci4_db
    restart: always
    environment:
      MYSQL_DATABASE: library_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ciuser
      MYSQL_PASSWORD: cipassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
